select * from DBM.RES,RESOURCE
;-- -. . -..- - / . -. - .-. -.--
select * from DBM.RES.RESOURCE
;-- -. . -..- - / . -. - .-. -.--
insert into DBM_RES_RESOURCE(RES_ID) values ('5126fb4c')
;-- -. . -..- - / . -. - .-. -.--
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS WHERE TABLE_NAME='DBM_RES_RESOURCE'
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_RESSOURCE MODIFY(
  RES_ID varchar(8)
)
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_RESOURCE ALTER COLUMN  RES_ID varchar(8)
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_RESOURCE MODIFY COLUMN  RES_ID varchar(8)
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_RESOURCE MODIFY (RES_ID varchar(8))
;-- -. . -..- - / . -. - .-. -.--
SELECT * from tabs
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_PROP MODIFY (RES_ID varchar2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_RESOURCE MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_PROP MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_FILE MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_GROUP_CFG MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_WORKINGSET_ENTRY MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_SHORTCUTBAR MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_CFG_STATUS MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_CFG_HISTORY MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_CFG_PROP MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_EVT_CONF MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_MON_MONITOR MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_MON_MONITORPARAM MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_USR_PRIVILEGE MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_BIZ_CFGPATH MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_USR_DEF_WIDGET_RES MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_USR_REP_WIDGET_RES MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_USER_CRITERIA MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_TPR_REPORT_INFO MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
ALTER TABLE DBM_RES_SYSEVENT MODIFY (RES_ID VARCHAR2(8))
;-- -. . -..- - / . -. - .-. -.--
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH FROM USER_TAB_COLUMNS WHERE TABLE_NAME='DBM_RES_RESOURCE'
;-- -. . -..- - / . -. - .-. -.--
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH FROM USER_TAB_COLUMNS WHERE TABLE_NAME='DBM_RES_SYSEVENT'
;-- -. . -..- - / . -. - .-. -.--
select * from DBM_RES_RESOURCE
;-- -. . -..- - / . -. - .-. -.--
SELECT SUM(CLNT.TOT_SES_CNT) TOTAL_SESS_CNT, SUM(CLNT.ACT_SES_CNT) ACTIVE_SESS_CNT
FROM DBM_ST_CLIENT_S CLNT, (SELECT RES_ID, CFG_PATH, STAT_DATE FROM
(SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S, (SELECT RES_ID RID FROM DBM_RES_RESOURCE WHERE RES_ID = '357bc140' AND ROWNUM < 2) R WHERE STAT_DATE > TO_CHAR(SYSTIMESTAMP - 20/24/60/60, 'YYYYMMDDHH24MISS')
AND RES_ID = R.RID AND CFG_PATH = 'config001')
WHERE ROWNUM < 2 ) LAST_TS WHERE CLNT.RES_ID = LAST_TS.RES_ID
AND CLNT.CFG_PATH = LAST_TS.CFG_PATH
AND CLNT.STAT_DATE = LAST_TS.STAT_DATE
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID RID FROM DBM_RES_RESOURCE WHERE RES_ID = '357bc140' AND ROWNUM < 2
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID RID FROM DBM_RES_RESOURCE WHERE RES_NAME = 'PostMan' AND ROWNUM < 2
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S, (SELECT RES_ID RID FROM DBM_RES_RESOURCE WHERE RES_NAME = 'PostMan' AND ROWNUM < 2) R WHERE STAT_DATE > TO_CHAR(SYSTIMESTAMP - 20/24/60/60, 'YYYYMMDDHH24MISS')
AND RES_ID = R.RID AND CFG_PATH = 'config001'
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S WHERE STAT_DATE > TO_CHAR(SYSTIMESTAMP - 20/24/60/60, 'YYYYMMDDHH24MISS')
AND RES_ID = '357bc140' AND CFG_PATH = 'config001'
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S WHERE STAT_DATE > TO_CHAR(SYSTIMESTAMP - 20/24/60/60, 'YYYYMMDDHH24MISS'
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S WHERE STAT_DATE > TO_CHAR(SYSTIMESTAMP - 20/24/60/60, 'YYYYMMDDHH24MISS')
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S2
;-- -. . -..- - / . -. - .-. -.--
SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S
;-- -. . -..- - / . -. - .-. -.--
SELECT SUM(CLNT.TOT_SES_CNT) TOTAL_SESS_CNT, SUM(CLNT.ACT_SES_CNT) ACTIVE_SESS_CNT
FROM DBM_ST_CLIENT_S CLNT, (SELECT RES_ID, CFG_PATH, STAT_DATE FROM
(SELECT RES_ID, CFG_PATH, STAT_DATE FROM DBM_ST_CLIENT_S WHERE STAT_DATE > TO_CHAR(SYSTIMESTAMP - 20/24/60/60, 'YYYYMMDDHH24MISS')
AND RES_ID = '357bc140' AND CFG_PATH = 'config001')
WHERE ROWNUM < 2 ) LAST_TS WHERE CLNT.RES_ID = LAST_TS.RES_ID
AND CLNT.CFG_PATH = LAST_TS.CFG_PATH
AND CLNT.STAT_DATE = LAST_TS.STAT_DATE
;-- -. . -..- - / . -. - .-. -.--
SELECT * FROM DBM_ST_CLIENT_S